### ISSUE TITLE
having problem in mail loop via header

### ISSUE THREAD

**Issue by hitasoft** [thunderkeys/pdfconvertme-public#1]
Can some one please help me with this error.

Error:
Command died with status 255: "/usr/bin/perl
    /usr/local/bin/pdfconvertme.pl --force-markdown". Command output: Detected
    a mail loop via header 'In-Reply-To:
    db0d3295c568369d22d0af1ff9133046b51.20150415152025@mail171.atl21.rsgsv.net',
    aborting! at /usr/local/bin/pdfconvertme.pl line 272, <> line 500.

Final-Recipient: rfc822; pdfconvert@****_.com
Original-Recipient: rfc822;pdfconvert@**_**.com
Action: failed
Status: 5.3.0
Diagnostic-Code: x-unix; Detected a mail loop via header 'In-Reply-To:
    db0d3295c568369d22d0af1ff9133046b51.20150415152025@mail171.atl21.rsgsv.net',
    aborting! at /usr/local/bin/pdfconvertme.pl line 272, <> line 500.

**Comment by thunderkeys** [comment]
Hi,

Typically I don't expect to see an In-Reply-To: header on a conversion request as it usually indicates an autoresponder of some sort.  If you can forward a sample raw message that exhibits this behavior to bma@pdfconvert.me, I can take a closer look.

Thanks,

Brian

**Comment by hitasoft** [comment]
Hello Brian

Thanks for your support. As you suggested I commented the lines 272/273 (pdfconvert.pl) and its works fine now. I have one last questions and some other things I have done to get it work.

Wow ! It worked. Just for a better understanding this is what I used.
1. There was problem in the pdfconvert.pl file. The mail_attachment.sh file path is not given as full path. So, I was about to change it to get it work.
2. Then I had the problem of this mail loop issue in form of in_reply_to. After commenting the lines you mentioned, it worked. 
3. Now, the email are sending with "Unknown sender" and the "from:" tag is empty. Can you please tell me what should I do to make it work?

Thanks for your prompt support.

**Comment by thunderkeys** [comment]
Hello,

Sorry for not closing the loop on this.  I've pushed out a fix today for issue #1 (commit 6ae3c1a) and there is also a --force-from option you can specify to manually set the from that may fix #3 (located in commit 285fe87).

For #2 - I've made a variable at the top of the script where you can disable this (located in commit 58b0fc9).

Let me know if you have any further questions or issues.

Brian
