### ISSUE TITLE
command for linux

### ISSUE THREAD

**Issue by dipenpatel235** [thunderkeys/pdfconvertme-public#2]
hello..
can u please give full command for convert pdf to word file.
i have try using ./bin/pdfconvertme.pl --pdf-to-word /root/sample.pdf 
but now worked

**Comment by thunderkeys** [comment]
If you want to just convert PDF to word via commandline you can use the bin/pdf2word.sh script, e.g.

bin/pdf2word.sh /path/to/output/word.docx /path/to/input.pdf
