### ISSUE TITLE
Broken when file has Unicode Filename with asian characters

### ISSUE THREAD

**Issue by stevennt** [thunderkeys/pdfconvertme-public#4]
I encountered the following error with unicode file name:

Issue: the script fails to process the file with the following kind of name: Báo Cáo Tuần.docx
Environment: Standard Debian 10.
File names without these unicode characters are processed fine. 

Is there any special environment required for this script to work? I tested sending the file to attachconvert@pdfconvert.me and it worked, not sure if any different configuration is done there. 
Thanks.

**Comment by thunderkeys** [comment]
What is the exact error you are getting? I tested an email with that filename in standalone mode and while it gave some errors on the console it did successfully convert.  are you able to email me a sample raw .eml file containing the problem (bma@pdfconvert.me)

it is probably related to this upstream bug in Email::MIME::ContentType: https://www.perlmonks.org/bare/?node_id=1227686

**Comment by thunderkeys** [comment]
fixed a few years ago, never closed out.

commit cec6bc925f74c2d7f997a2f131a4d6b6d82c0e8d
Author: Brian Almeida <bma@thunderkeys.net>
Date:   Sat Mar 28 20:24:01 2020 -0400

    Fix for more recent Email::MIME::ContentType and UTF-8 filenames
