### ISSUE TITLE
Attachment conversion and other issues

### ISSUE THREAD

**Issue by rules76** [thunderkeys/pdfconvertme-public#6]
Hi,
first of all, I'd like to make a big THANKS to developers for this open-source version.
I've installed it on an Ubuntu VM... fetchmail+procmail to process mail.. it works good!
I have some questions:
1) image attachments are converted also without --convert-attachment switch (but my $attachments_enabled = 1; GLOBALS in pdfconvertme.pl is enabled)....is it correct?
2) I'm facing troubles with Office attachment conversion, it doesn't work; it seems that it's trying to be converted using imagemagick! (error in procmail.log ->> convert-im6.q16: attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/408.) I think that it depends to image in email signature that is tretaed as first attachment and then it will be processed instead of true attachment (like https://github.com/thunderkeys/pdfconvertme-public/issues/5#issue-645609863)
3) Italian characters link ì à ò (ecc...) are not correctly converted (wrong encoding?)

Thank you very much
Marco

**Comment by thunderkeys** [comment]
Hi Marco,
 
1) The attachments_enabled flag is paired with the explicit --convert-attachment flag -- inline images/attached images don't need that flag.
2) Yes, that's likely what is happening.  I have some ideas but the easiest way to work around that is to disable your signature when sending in a non-image attachment conversion request.
3) Make sure your system is setup with UTF-8 as well as has all the necessary fonts installed on the system. It should all work with international character sets.

Thanks

Brian

**Comment by rules76** [comment]
Thank you very much for your suggestions.
Marco
